### ISSUE TITLE
*minimum* relative humidity for CFWI?

### ISSUE THREAD

**Issue by yquilcaille** [NCAR/fire-indices#4]
Hi, I plan on calculating the CFWI on CMIP6 data and noticed this code.

I see that you recommend as inputs for the CFWI:
> CFWI is the Canadian Fire Weather Index. Its inputs are daily surface windspeed, daily maximum temperature, daily relative humidity, and daily precipitation. Some datasets do not have average daily humidity, in which case use the inputs of daily max and min humidities, averaged together. The code can read in either average humidity or daily max and min, with the max and min version currently commented out.

However, according to [https://cfs.nrcan.gc.ca/publications?id=36461](url), the CFWI requires inputs at noon local time.
> The FWI System depends solely on weather measurements taken each day at noon local time.

Which is why the daily maximum temperature, to have a sense of the temperature at noon local time. Then why not using only the daily minimum relative humidity for the same reason? The daily average or maximum relative humidity may not be the appropriate proxy for noon relative humidity? This is the operation performed in [https://doi.org/10.1029/2018GL080959](url).

(tagging a colleague interested in the same question as well: @fuldenica )

**Comment by sethmcg** [comment]
That's a good point.  If you have the option of choosing from daily average or daily maximum relative humidity, I think you're right that the latter would be a better match for noon measurements.  Most of the datasets we are working with only have daily average values, so our practice has been to estimate daily average from the minimum and maximum because we need the datasets to be consistent with one another for the work we're doing, but in general it would be good practice to use maximum values where feasible.  Thanks for pointing this out; we'll update the comments appropriately.

**Comment by fuldenica** [comment]
Dear Dr. McGinnis,

We have contacted you before regarding the Canadian Fire Weather Index in
https://github.com/NCAR/fire-indices
My colleague (cc'd) and I calculated CFWI using different source codes and
we realized that the given ranges to classify fire danger are different. In
your description the ranges are;

0-5 is considered low fire danger, 5-10 is moderate, 10-20 is high, 20-30
is very high, and anything greater than 30 is considered extreme.

The one that my colleague uses has the following ranges;

The fire weather index can be categorised into 6 classes of danger as
follows: Very low danger: FWI is less than 5.2. Low danger: FWI is between
5.2 and 11.2. Moderate danger: FWI is between 11.2 and 21.3. High danger:
FWI is between 21.3 and 38.0. Very high danger: FWI is between 38.0 and 50.
Extreme danger: FWI is greater than 50.

We were wondering what could be the reason for these differences and if you
were aware of this situation?
Thanks a lot in advance.

Best regards,
Fulden Batibeniz
PostDoc | ETH Zurich

**Comment by akessenich** [comment]
Hi Dr. Batibeniz,

While I do not recognize the exact ranges of values used by your colleague at first glance, I am aware that different thresholds exist. I can attempt to give a brief response on the reasons why. 

In my experience, ranges of exact numbers work locally, not broadly. I was planning on removing that language from our description because of that. The precise range and distribution of CFWI changes based on its inputs. If proxy variables are used (most likely either maximum temperature and minimum relative humidity or average temperature and average relative humidity), the range of values will shift. It also depends on the type of data being used (point-based observations or gridded data and associated grid-spacing). The original recommended ranges that are in the description of our code most likely comes from CFWI documentation that used noon-day temperature and relative humidity for Canadian forests. I do not use those bins for classification of fire danger because it wouldn't translate precisely to CFWI calculated with proxy variables, which is what I work with.

The more localized and precise of thresholds that can be used, the better.

Please let me know if there is anything more to discuss.

Cheers,
Lee Kessenich
